name: GitHub Actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  python-version:
    runs-on: ubuntu-latest
    steps:
    - name: Show Python version
      run: python --version

  pylint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install requirements
      run: pip install -r requirements.txt
    - name: Start Pylint
      run: pylint app.py
